### ISSUE TITLE
GDAL bindings performance improvements

### ISSUE THREAD

**Issue by pomadchin** [geotrellis/geotrellis-contrib#146]
@metasim [prepared integration tests](https://github.com/geotrellis/geotrellis-contrib/pull/137) to test GDAL / GeoTrellis Java TIFF Readers performance.

**Command to to run tests:**
```bash
$ ./sbt
> project gdal
> it:testOnly geotrellis.contrib.vlm.SubsceneReadingIT
```

The current test log: 

```bash
[info] Done compiling.
[info] SubsceneReadingIT:
[info] GDAL vs GeoTrellis GeoTiff reading
23:28:20 SubsceneReadingIT: Elapsed time of GeoTrellis is 2.0670s, producing ProjectedExtent(Extent(3440101.0175691093, -2315767.899836476, 3462532.0983280675, -2294035.527693799),EPSG:3857)
23:28:26 SubsceneReadingIT: Elapsed time of GDAL is 5.7390s, producing ProjectedExtent(Extent(3440101.0175691093, -2315767.899836476, 3462532.0983280675, -2294035.527693799),merc-CS)
[info] - should read projected extent with similar performance with GDAL *** FAILED *** (7 seconds, 941 milliseconds)
[info]   2067.0 was not 5739.0 plus or minus 1000.0 (SubsceneReadingIT.scala:59)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:346)
[info]   at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:6668)
[info]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6704)
[info]   at geotrellis.contrib.vlm.SubsceneReadingIT$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(SubsceneReadingIT.scala:59)
[info]   at geotrellis.contrib.vlm.SubsceneReadingIT$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(SubsceneReadingIT.scala:45)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.FunSpecLike$$anon$1.apply(FunSpecLike.scala:454)
[info]   at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
[info]   at org.scalatest.FunSpec.withFixture(FunSpec.scala:1630)
[info]   at org.scalatest.FunSpecLike$class.invokeWithFixture$1(FunSpecLike.scala:451)
[info]   at org.scalatest.FunSpecLike$$anonfun$runTest$1.apply(FunSpecLike.scala:464)
[info]   at org.scalatest.FunSpecLike$$anonfun$runTest$1.apply(FunSpecLike.scala:464)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
[info]   at org.scalatest.FunSpecLike$class.runTest(FunSpecLike.scala:464)
[info]   at org.scalatest.FunSpec.runTest(FunSpec.scala:1630)
[info]   at org.scalatest.FunSpecLike$$anonfun$runTests$1.apply(FunSpecLike.scala:497)
[info]   at org.scalatest.FunSpecLike$$anonfun$runTests$1.apply(FunSpecLike.scala:497)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
[info]   at scala.collection.immutable.List.foreach(List.scala:392)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:373)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:410)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
[info]   at scala.collection.immutable.List.foreach(List.scala:392)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
[info]   at org.scalatest.FunSpecLike$class.runTests(FunSpecLike.scala:497)
[info]   at org.scalatest.FunSpec.runTests(FunSpec.scala:1630)
[info]   at org.scalatest.Suite$class.run(Suite.scala:1147)
[info]   at org.scalatest.FunSpec.org$scalatest$FunSpecLike$$super$run(FunSpec.scala:1630)
[info]   at org.scalatest.FunSpecLike$$anonfun$run$1.apply(FunSpecLike.scala:501)
[info]   at org.scalatest.FunSpecLike$$anonfun$run$1.apply(FunSpecLike.scala:501)
[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
[info]   at org.scalatest.FunSpecLike$class.run(FunSpecLike.scala:501)
[info]   at org.scalatest.FunSpec.run(FunSpec.scala:1630)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
[info]   at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:304)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[info]   at java.lang.Thread.run(Thread.java:748)
23:28:29 SubsceneReadingIT: Elapsed time of GeoTrellis is 3.1690s, producing Some(372620)
23:28:31 SubsceneReadingIT: Elapsed time of GDAL is 1.6730s, producing Some(372620)
[info] - should be faster reading subextent with GDAL (4 seconds, 846 milliseconds)
23:28:32 SubsceneReadingIT: reading 600 tiles
23:29:27 SubsceneReadingIT: Elapsed time of GeoTrellis is 55.9890s, producing 37194588
23:30:12 SubsceneReadingIT: Elapsed time of GDAL is 44.7290s, producing 37194588
[info] - should be faster reading full scene as tiles with GDAL (1 minute, 40 seconds)
23:30:57 SubsceneReadingIT: Elapsed time of GeoTrellis is 45.5780s, producing 37194588
23:30:57 SubsceneReadingIT: Elapsed time of GDAL is 0.0570s, producing 37194588
[info] - should be faster reading full scene GDAL (45 seconds, 640 milliseconds)
```

It's obvious that GDAL bindings a slower in fetching *metadata*. It looks like in a near future we also would be required to fetch along with `extent`, `crs`, `cellType` and `cellSize` to get all the **TiffTag**.

Also it looks like sometimes reading the full scene can be a bit longer than using GeoTrellis Java Readers. I think it's related to the number of opened `Datasets`. 

So these integration tests should always pass.

**Comment by metasim** [comment]
Super awesome you guys got the others tests running so much faster! Keep an eye out for lazy evaluation. I tried to work around it, but that  second to last line seem suspicious to me.

**Comment by metasim** [comment]
FWIW, In our use cases, reading metadata before the whole raster is so important that we'd have to consider a dual mode whereby the header is read with the JVM reader and the raster data with GDAL.

Related: https://github.com/geotrellis/geotrellis-contrib/issues/141

**Comment by pomadchin** [comment]
@metasim check it out: https://github.com/geotrellis/geotrellis-contrib/pull/148/files 
It's more likely a GDAL configuration thing.

**Comment by pomadchin** [comment]
@metasim pay attention to geotrellis-contrib versions, since the latest `0.10.2` release we don't depend on the official GDAL JNI bindings at all. Can you review all your issues related to it and comments?
