### ISSUE TITLE
GDALRasterSource does not use options

### ISSUE THREAD

**Issue by echeipesh** [geotrellis/geotrellis-contrib#81]
When trying to read AWS terrain tiles the following error happens:
```
[error] ERROR 1: DoSinglePartPUT of /vsis3/elevation-tiles-prod/v2/skadi/N89/N89E179.hgt.gz.properties failed
```

In theory it can be avoided by passing correct `oo` option:
```scala
GDALRasterSource(uri, GDALWarpOptions(oo=List(("CPL_VSIL_GZIP_WRITE_PROPERTIES", "NO"))))
```

however the `option` argument is never used in the `GDALBaseRasterSource`.

**Comment by pomadchin** [comment]
It's used only in [Reproject](https://github.com/geotrellis/geotrellis-contrib/blob/master/vlm/src/main/scala/geotrellis/contrib/vlm/gdal/GDALReprojectRasterSource.scala#L59) and in [Resample](https://github.com/geotrellis/geotrellis-contrib/blob/master/vlm/src/main/scala/geotrellis/contrib/vlm/gdal/GDALResampleRasterSource.scala#L58). Needs to be added [there](https://github.com/geotrellis/geotrellis-contrib/blob/master/vlm/src/main/scala/geotrellis/contrib/vlm/gdal/GDALRasterSource.scala#L25) as an options as `lazy val warpOptions: GDALWarpOptions = options`

**Comment by echeipesh** [comment]
Something odd is going on, the options are still not being used the first time, the second the dataset is invoked the error goes away ...

```scala
Welcome to Scala 2.11.12 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_181).
Type in expressions for evaluation. Or try :help.

scala> val rs1 = GDALRasterSource(url, GDALWarpOptions(oo=List(("CPL_VSIL_GZIP_WRITE_PROPERTIES", "NO"))))import geotrellis.contrib.vlm._
import geotrellis.contrib.vlm.geotiff._
import geotrellis.contrib.vlm.gdal._
import geotrellis.gdal._
import geotrellis.gdal._

scala> val url = "s3://elevation-tiles-prod/v2/skadi/N89/N89E179.hgt.gz"
url: String = s3://elevation-tiles-prod/v2/skadi/N89/N89E179.hgt.gz

scala> val rs1 = GDALRasterSource(url, GDALWarpOptions(oo=List(("CPL_VSIL_GZIP_WRITE_PROPERTIES", "YES"))))
rs1: geotrellis.contrib.vlm.gdal.GDALRasterSource = GDALRasterSource(s3://elevation-tiles-prod/v2/skadi/N89/N89E179.hgt.gz,GDALWarpOptions(Some(VRT),None,None,None,true,None,None,None,None,List(),List(),Some(AutoHigherResolution),List(),false,None,false,false,false,None,List(),None,None,false,false,false,None,false,false,List(),None,None,None,None,None,false,false,false,None,false,List((CPL_VSIL_GZIP_WRITE_PROPERTIES,YES)),List(),List(),None))

scala> rs1.extent
geotrellis.gdal.GDALException: GDAL ERROR 1: DoSinglePartPUT of /vsis3/elevation-tiles-prod/v2/skadi/N89/N89E179.hgt.gz.properties failed
  at geotrellis.gdal.GDALException$.lastError(GDAL.scala:36)
  at geotrellis.gdal.GDAL$.openPath(GDAL.scala:62)
  at geotrellis.gdal.GDAL$.open(GDAL.scala:52)
  at geotrellis.gdal.GDAL$$anonfun$3.apply(GDAL.scala:94)
  at geotrellis.gdal.GDAL$$anonfun$3.apply(GDAL.scala:86)
  at cats.instances.ListInstances$$anon$1.cats$instances$ListInstances$class$$anon$$step$1(list.scala:111)
  at cats.instances.ListInstances$$anon$1$$anonfun$foldM$1.apply(list.scala:114)
  at cats.instances.ListInstances$$anon$1$$anonfun$foldM$1.apply(list.scala:114)
  at cats.instances.EitherInstances$$anon$1.tailRecM(either.scala:51)
  at cats.instances.EitherInstances$$anon$1.tailRecM(either.scala:32)
  at cats.instances.ListInstances$$anon$1.foldM(list.scala:114)
  at cats.instances.ListInstances$$anon$1.foldM(list.scala:12)
  at cats.Foldable$class.foldLeftM(Foldable.scala:284)
  at cats.instances.ListInstances$$anon$1.foldLeftM(list.scala:12)
  at cats.Foldable$Ops$class.foldLeftM(Foldable.scala:31)
  at cats.Foldable$ToFoldableOps$$anon$6.foldLeftM(Foldable.scala:31)
  at geotrellis.gdal.GDAL$.fromGDALWarpOptions(GDAL.scala:86)
  at geotrellis.contrib.vlm.gdal.GDALBaseRasterSource$class.dataset(GDALBaseRasterSource.scala:66)
  at geotrellis.contrib.vlm.gdal.GDALRasterSource.dataset$lzycompute(GDALRasterSource.scala:22)
  at geotrellis.contrib.vlm.gdal.GDALRasterSource.dataset(GDALRasterSource.scala:22)
  at geotrellis.contrib.vlm.gdal.GDALBaseRasterSource$class.rasterExtent(GDALBaseRasterSource.scala:79)
  at geotrellis.contrib.vlm.gdal.GDALRasterSource.rasterExtent$lzycompute(GDALRasterSource.scala:22)
  at geotrellis.contrib.vlm.gdal.GDALRasterSource.rasterExtent(GDALRasterSource.scala:22)
  at geotrellis.contrib.vlm.RasterSource$class.extent(RasterSource.scala:74)
  at geotrellis.contrib.vlm.gdal.GDALRasterSource.extent(GDALRasterSource.scala:22)
  ... 40 elided

scala> val rs1 = GDALRasterSource(url, GDALWarpOptions(oo=List(("CPL_VSIL_GZIP_WRITE_PROPERTIES", "YES"))))
rs1: geotrellis.contrib.vlm.gdal.GDALRasterSource = GDALRasterSource(s3://elevation-tiles-prod/v2/skadi/N89/N89E179.hgt.gz,GDALWarpOptions(Some(VRT),None,None,None,true,None,None,None,None,List(),List(),Some(AutoHigherResolution),List(),false,None,false,false,false,None,List(),None,None,false,false,false,None,false,false,List(),None,None,None,None,None,false,false,false,None,false,List((CPL_VSIL_GZIP_WRITE_PROPERTIES,YES)),List(),List(),None))

scala> rs1.extent
res1: geotrellis.vector.Extent = Extent(178.9998611111111, 88.99986111111112, 180.00013888888887, 90.00013888888888)
```

worth mentioning that it doesn't matter if property is set to `NO` or `YES`, so I'm not convinced this is the same issue. But related, you know.

**Comment by pomadchin** [comment]
Ah, I know what's going on. GDAL usually scans the entire dir not only reads a single URI passed. It's required to fetch external overviews, VRTs and other metadata information. It looks like this thing works unordered / sometimes corrupted / or it's a GDAL bug / feature.

The solution is to disable this GDAL options:

```scala
import org.gdal.gdal.gdal
gdal.SetConfigOption("GDAL_DISABLE_READDIR_ON_OPEN", "YES")
```

The full example:

```scala
sbt:geotrellis-contrib-vlm> console
[info] Compiling 1 Scala source to /Users/daunnc/subversions/git/github/pomadchin/geotrellis-contrib/vlm/target/scala-2.11/classes ...
[info] Done compiling.
[info] Starting scala interpreter...
Welcome to Scala 2.11.12 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_162).
Type in expressions for evaluation. Or try :help.

scala> import geotrellis.contrib.vlm._
import geotrellis.contrib.vlm.geotiff._
import geotrellis.contrib.vlm.gdal._


scala> import geotrellis.gdal._
import geotrellis.gdal._

scala> import org.gdal.gdal.gdal
import org.gdal.gdal.gdal

scala> gdal.SetConfigOption("GDAL_DISABLE_READDIR_ON_OPEN", "YES")

scala> val url = "s3://elevation-tiles-prod/v2/skadi/N89/N89E179.hgt.gz"
url: String = s3://elevation-tiles-prod/v2/skadi/N89/N89E179.hgt.gz

scala> val rs1 = GDALRasterSource(url)
rs1: geotrellis.contrib.vlm.gdal.GDALRasterSource = GDALRasterSource(s3://elevation-tiles-prod/v2/skadi/N89/N89E179.hgt.gz,GDALWarpOptions(Some(VRT),None,None,None,true,None,None,None,None,List(),List(),Some(AutoHigherResolution),List(),false,None,false,false,false,None,List(),None,None,false,false,false,None,false,false,List(),None,None,None,None,None,false,false,false,None,false,List(),List(),List(),None))

scala> rs1.extent
res1: geotrellis.vector.Extent = Extent(178.9998611111111, 88.99986111111112, 180.00013888888887, 90.00013888888888)
```

**Comment by pomadchin** [comment]
Ok, the solution was closed. So it's a feature related to how GDAL works with `.gz` format ([the related issue with a fix](https://trac.osgeo.org/gdal/ticket/7016)).

The final solution is to set:

```scala
gdal.SetConfigOption("CPL_VSIL_GZIP_WRITE_PROPERTIES", "NO")
```

```scala
sbt:geotrellis-contrib-vlm> console
[info] Starting scala interpreter...
Welcome to Scala 2.11.12 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_162).
Type in expressions for evaluation. Or try :help.

scala> :paste
// Entering paste mode (ctrl-D to finish)

import geotrellis.contrib.vlm._
import geotrellis.contrib.vlm.geotiff._
import geotrellis.contrib.vlm.gdal._

import geotrellis.gdal._
import org.gdal.gdal.gdal

gdal.SetConfigOption("CPL_VSIL_GZIP_WRITE_PROPERTIES", "NO")

val url = "s3://elevation-tiles-prod/v2/skadi/N89/N89E179.hgt.gz"

val rs1 = GDALRasterSource(url)

rs1.extent


// Exiting paste mode, now interpreting.

import geotrellis.gdal._
import org.gdal.gdal.gdal
url: String = s3://elevation-tiles-prod/v2/skadi/N89/N89E179.hgt.gz
rs1: geotrellis.contrib.vlm.gdal.GDALRasterSource = GDALRasterSource(s3://elevation-tiles-prod/v2/skadi/N89/N89E179.hgt.gz,GDALWarpOptions(Some(VRT),None,None,None,true,None,None,None,None,List(),List(),Some(AutoHigherResolution),List(),false,None,false,false,false,None,List(),None,None,false,false,false,None,false,false,List(),None,None,None,None,None,false,false,false,None,false,List(),List(),List(),None))
res0: geotrellis.vector.Extent = Extent(178.9998611111111, 88.99986111111112, 180.00013888888887, 90.00013888888888)
```

**Comment by echeipesh** [comment]
👍 thank you
